- name: 'api'
  color: 'fbca04'
- name: 'backlog'
  color: '7ef7ef'
- name: 'bug'
  color: 'd73a4a'
- name: 'ci'
  color: '0075ca'
- name: 'core'
  color: 'fbca04'
- name: 'dependencies'
  color: '276bd1'
- name: 'discussion'
  color: 'b6b1f9'
- name: 'documentation'
  color: '0075ca'
- name: 'duplicate'
  color: 'cfd3d7'
- name: 'feature request'
  color: 'fcf95a'
- name: 'good first issue'
  color: '7057ff'
- name: 'handler'
  color: 'fbca04'
- name: 'has PR'
  color: '4b1f8e'
- name: 'help wanted'
  color: '008672'
- name: 'in progress'
  color: 'ffccd7'
- name: 'in review'
  color: 'aed5fc'
- name: 'invalid'
  color: 'e4e669'
- name: 'need repro'
  color: 'c66037'
- name: 'priority:high'
  color: 'fc1423'
- name: 'question'
  color: 'd876e3'
- name: 'refactor'
  color: '1d637f'
- name: 'regression'
  color: 'ea8785'
- name: 'rest'
  color: 'fbca04'
- name: 'semver:major'
  color: 'c10f47'
- name: 'semver:minor'
  color: 'e4f486'
- name: 'semver:patch'
  color: 'e8be8b'
- name: 'tests'
  color: 'f06dff'
- name: 'types'
  color: 'fbca04'
- name: 'website'
  color: 'fbca04'
- name: 'wontfix'
  color: 'ffffff'
