project_id: '449484'
commit_message: 'chore(i18n): new translations for %original_file_name% (%language%) [skip ci]'
append_commit_message: false
base_path: .
preserve_hierarchy: true
files:
  - source: /packages/yuudachi/locales/en-US/translation.json
    translation: /packages/yuudachi/locales/%locale%/%original_file_name%
