FROM node:10-alpine
LABEL name "Yukikaze GraphQL"
LABEL version "0.1.0"
LABEL maintainer "iCrawl <icrawltogo@gmail.com>"
WORKDIR /usr/yukikaze
COPY api/src/package.json .yarnclean /usr/yukikaze/src/api/
COPY tsconfig.json yarn.lock .yarnclean /usr/yukikaze/
RUN apk add --update \
&& apk add --no-cache ca-certificates \
&& apk add --no-cache --virtual .build-deps git curl build-base python g++ make \
&& yarn install --ignore-engines \
&& apk del .build-deps
COPY api/src /usr/yukikaze/src/api/
EXPOSE 5000
WORKDIR /usr/yukikaze/src/api
RUN yarn build
ENV NODE_ENV= \
	OWNERS= \
	DB= \
	SENTRY= \
	LOKI= \
	GITHUB_API_KEY=
CMD ["node", "dist/index.js"]
