FROM node:10-alpine
LABEL name "Yukikaze Bot"
LABEL version "0.1.0"
LABEL maintainer "iCrawl <icrawltogo@gmail.com>"
WORKDIR /usr/yukikaze
COPY bot/src/package.json .yarnclean /usr/yukikaze/src/bot/
COPY tsconfig.json yarn.lock .yarnclean /usr/yukikaze/
RUN apk add --update \
&& apk add --no-cache ca-certificates \
&& apk add --no-cache --virtual .build-deps git curl build-base python g++ make \
&& yarn install --ignore-engines \
&& apk del .build-deps
COPY bot/src /usr/yukikaze/src/bot/
WORKDIR /usr/yukikaze/src/bot
RUN yarn build
ENV NODE_ENV= \
	COMMAND_PREFIX= \
	OWNERS= \
	TOKEN= \
	LOGS= \
	WEBHOOK_ID= \
	WEBHOOK_TOKEN= \
	DB= \
	SENTRY= \
	GITHUB_API_KEY=
CMD ["node", "dist/bot.js"]
