FROM node:10-alpine
LABEL name "Yukikaze GraphQL"
LABEL version "0.1.0"
LABEL maintainer "iCrawl <icrawltogo@gmail.com>"
WORKDIR /usr/src
COPY src/api/package.json .yarnclean /usr/src/yukikaze/api
COPY tsconfig.json yarn.lock .yarnclean /usr/src/
RUN apk add --update \
&& apk add --no-cache ca-certificates \
&& apk add --no-cache --virtual .build-deps git curl build-base python g++ make \
&& yarn install --ignore-engines \
&& apk del .build-deps
COPY src/api /usr/src/yukikaze/api
EXPOSE 5000
RUN yarn build
ENV NODE_ENV= \
	OWNERS= \
	DB= \
	SENTRY= \
	LOKI= \
	GITHUB_API_KEY=
CMD ["node", "dist/index.js"]
