FROM node:10-alpine
LABEL name "Yukikaze Dashboard"
LABEL version "0.1.0"
LABEL maintainer "iCrawl <icrawltogo@gmail.com>"
WORKDIR /usr/src/yukikaze/dashboard
COPY src/dashboard/package.json yarn.lock .yarnclean ./
COPY tsconfig.json yarn.lock .yarnclean /usr/src/
RUN apk add --update \
&& apk add --no-cache ca-certificates \
&& apk add --no-cache --virtual .build-deps git curl build-base python g++ make \
&& yarn install --ignore-engines \
&& apk del .build-deps
COPY src/dashboard .
EXPOSE 3200
RUN yarn build
ENV NODE_ENV= \
	DISCORD= \
	GRAPHQL=
CMD ["yarn", "start"]
