- args:
    sql: CREATE TABLE "public"."settings"("guild" text NOT NULL, "settings" jsonb
      NOT NULL DEFAULT jsonb_build_object(), PRIMARY KEY ("guild") );
  type: run_sql
- args:
    name: settings
    schema: public
  type: add_existing_table_or_view
