name: Node
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run Build
        run: yarn workspaces foreach --parallel --topological-dev run build

      - name: Run Tests
        run: yarn run test:ci

      - name: Upload Coverage
        uses: codecov/codecov-action@v1
