name: Node
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install Node v15
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 15

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Build packages
        run: yarn build

      - name: Run Tests
        run: yarn test:ci

      - name: Upload Coverage
        uses: codecov/codecov-action@v1.5.2
